twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        'assets/css': css
    globals:
        subscription_level_rights: "@app.subscription_level_rights"


when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_4_layout.html.twig']
